#!/bin/zsh

# Function to compare version strings
version_compare() {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

# Get current PowerShell version
current_version=$(pwsh -v | awk '{print $2}')

# Fetch latest version from GitHub API
latest_version=$(curl -s https://api.github.com/repos/PowerShell/PowerShell/releases/latest | grep -oP '"tag_name": "v\K(.*)(?=")')

echo "Current version: $current_version"
echo "Latest version: $latest_version"

# Compare versions
version_compare $current_version $latest_version
case $? in
    0) echo "PowerShell is up to date." ;;
    2) echo "PowerShell update available!"
       read -q "response?Do you want to update? (y/N) "
       echo
       if [[ $response =~ ^[Yy]$ ]]
       then
           echo "Updating PowerShell..."
           brew update && brew upgrade powershell
           echo "PowerShell updated to version $latest_version"
       else
           echo "Update cancelled."
       fi
       ;;
    *) echo "Error comparing versions." ;;
esac
