name: Push to GitHub

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  push_to_github:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push to GitHub
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add github https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/dagz55/wfh-automation.git
        git push github HEAD:main --force
